console.log(typeof "Felipe");  // "string"
console.log(typeof 10);        // "number"
console.log(typeof 5.1);       // "number"
console.log(typeof true);      // "boolean"
console.log(typeof undefined); // "undefined"
console.log(typeof null);      // "object"